# Exemplo 01 Makefile
#
# Help about Makefiles:
# http://mrbook.org/blog/tutorials/make/
#
# Syntax:
#	target: dependencies
#	[tab] system command

CC = g++
SOURCES = *.cpp

all:
	$(CC) $(FLAGS) -c $(SOURCES)
    
clean:
    rm -f *.o